project:
  type: website
  output-dir: _site

website:
  title: "Line by Line"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - posts.qmd
      - gallery.qmd
      - notes.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/sim-so
      # - icon: twitter
      #   href: https://twitter.com
  site-url: https://sim-so.github.io
  favicon: images/pavicon.png
  open-graph: 
    image: images/1200x630.png
  twitter-card: 
    image: images/1200x630.png
      

format:
  html:
    toc: true
    theme: 
      light: [cosmo, custom.scss]
      # dark: [cosmo, custom-dark.scss]
# css: styles.css
    
execute:
  freeze: auto