project:
  type: website
  output-dir: docs

website:
  title: "sim-so.github.io"
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - about.qmd
      - posts/index.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


