project:
  type: website
  output-dir: docs

website:
  title: "sim-so.github.io"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - blog/index.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  site-url: https://sim-so.github.io
  favicon: docs/images/pavicon.png
  open-graph: 
    image: docs/images/1200x630.png
  twitter-card: 
    image: docs/images/1200x630.png

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


