project:
  type: website
  output-dir: docs

website:
  title: "sim-so.github.io"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - blog/index.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  favicon: pavicon.png
  open-graph: 
    image: https://github.com/sim-so/sim-so.github.io/blob/663deb028064b501b81b8a29c7b8466db3ddb715/1200x630.png
  twitter-card: 
    image: https://github.com/sim-so/sim-so.github.io/blob/663deb028064b501b81b8a29c7b8466db3ddb715/1200x630.png

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


